### ISSUE TITLE
Illegal string offset 'b'

### ISSUE THREAD

**Issue by rikiless** [mtownsend5512/xml-to-array#5]
I've got this error, when value in XML is HTML is not encoded or wrapped into CDATA ([info](https://stackoverflow.com/a/1398976/1921661)).

Example:

```xml
<content>This is <b>bold</b></content>
```

Is there option how to handle this error and continue parsing XML?

**Comment by mtownsend5512** [comment]
Would you be able to provide the complete XML so I can take a look at it?

**Comment by rikiless** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<activities>
    <course>
        <purpose>
            Reference site about <b>Lorem Ipsum</b>, giving information on its origins, as well as a random Lipsum generator.
        </purpose>
        <content>
            <![CDATA[More info <a href= "http://www.site">**here**</a>]]>
        </content>
    </course>
</activities>
```

![Screen Shot 2020-02-11 at 06 15 10](https://user-images.githubusercontent.com/589851/74212780-3834a100-4c96-11ea-9f4f-47ecbc219f74.png)

**Comment by mtownsend5512** [comment]
Sorry for being so late to reply to this.

So, after looking at this, it _technically_ is valid XML. But it's not correct XML. CDATA exists to escape characters. The source should be wrapping that field in CDATA tags. Adding support for modifying XML before the class transforms it is outside the scope of what this package is trying to accomplish.

**Comment by rikiless** [comment]
Ok, thank you.
